
# database
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
        url: jdbc:mysql://101.101.211.97:3306/easyvalet?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        # url: jdbc:log4jdbc:mysql://101.101.211.97:3306/easyvalet?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        username: atom
        password: Easyvalet123!
        driver-class-name: com.mysql.cj.jdbc.Driver
#com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  config: mybatis-config.xml
  type-aliases-package: com.ohho.valetparking.domains.*
  mapper-locations: mybatis/mapper/*.xml