
# database
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
        url: jdbc:log4jdbc:mysql://localhost:3306/easyvalet?characterEncoding=utf8
        username: root
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  config: mybatis-config.xml
  type-aliases-package: com.ohho.valetparking.domains.*
  mapper-locations: mybatis/mapper/*.xml