version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'  

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.1
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8200:8200
    networks:
      - elastic
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/


volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge

  # Setting VM options -- VM options is 'Run >> Edit Configuration >> Modify Option' in  IntelliJ
  #
  #  -javaagent:/Users/loganjeong/Projects/valetparking/src/elastic-apm-agent-1.34.1.jar
  #  -Delastic.apm.service_name=easyvalet
  #  -Delastic.apm.server_urls=http://localhost:8200
  #  -Delastic.apm.application_packages=com.ohho.valetparking
  #  -Delastic.apm.transaction_sample_rate=1
  #  -Delastic.apm.trace_methods=com.ohho.*
  #  -Delastic.apm.span_frames_min_duration=1ms
  #  -Delastic.apm.span_min_duration=0ms
  #  -Delastic.apm.trace_methods_duration_threshold=1ms
  #  -Delastic.apm.transaction_sample_rate=1
  #  -Delastic.apm.enable_log_correlation=true
  #  -Delastic.apm.max_queue_size=2048