# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request CI

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VALET_SECRET_KEY: ${{ secrets.VALET_SECRET_KEY }}
      VALET_DB_USERNAME: ${{ secrets.VALET_DB_USERNAME }}
      VALET_DB_PASSWORD: ${{ secrets.VALET_DB_PASSWORD }}
      VALET_DB_URL: ${{ secrets.VALET_DB_URL }}
      VALET_DB_PORT: ${{ secrets.VALET_DB_PORT }}
      VALET_REFRESHTOKENTIME: ${{ secrets.VALET_REFRESHTOKENTIME }}
      VALET_ACCESSTOKENTIME: ${{ secrets.VALET_ACCESSTOKENTIME }}
      VALET_REDIS_SESSION_URL: ${{ secrets.VALET_REDIS_SESSION_URL }}  
    steps:
     - name: enviro test
       run: echo $VALET_DB_URL
       
     - name: Checkout
       uses: actions/checkout@v3

     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
          java-version: '11'
          distribution: 'temurin'
 
     - name: Set Gradle
       run: chmod +x gradlew
       
     - name: Test with Gradle
       run: ./gradlew test
       shell: bash   
    
     - name: Build with Gradle
       run: ./gradlew build
       shell: bash    
