name: Remote Delivery and Deploy
on: 
  push:
    branches:
      - main      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VALET_SECRET_KEY: ${{ secrets.TOKEN_SECRET }}
      VALET_DB_USERNAME: ${{ secrets.DB_USER }}
      VALET_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      VALET_DB_URL: ${{ secrets.DB_HOST }}
      VALET_DB_PORT: ${{ secrets.DB_PORT }}
      VALET_REFRESHTOKENTIME: ${{ secrets.REFRESHTOKENTIME }}
      VALET_ACCESSTOKENTIME: ${{ secrets.ACCESSTOKENTIME }}
    steps:
     - name: enviro test
       run: echo $VALET_DB_URL
       
     - name: Checkout
       uses: actions/checkout@v3

     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
          java-version: '11'
          distribution: 'temurin'
 
     - name: Set Gradle
       run: chmod +x gradlew

     - name: Build with Gradle
       run: ./gradlew build
       shell: bash    
       
     - name: location for Delivery
       uses: appleboy/scp-action@master
       with:
         host: ${{ secrets.HOST_IP }}
         username: ${{ secrets.HOST_ID }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.HOST_PORT }}
         source: "build/libs/*.jar"
         target: "source"
         rm: true


     - name: executing remote ssh commands using key
       uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
       with:
         host: ${{ secrets.HOST_IP }}
         username: ${{ secrets.HOST_ID }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.HOST_PORT }}
         script_stop: true
         script: |
                ./app_stop.sh
                ./app_start.sh
                exit
