name: Remote Delivery and Deploy
on: 
  push:
    branches:
      - main      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VALET_SECRET_KEY: ${{ secrets.VALET_SECRET_KEY }}
      VALET_DB_USERNAME: ${{ secrets.VALET_DB_USERNAME }}
      VALET_DB_PASSWORD: ${{ secrets.VALET_DB_PASSWORD }}
      VALET_DB_URL: ${{ secrets.VALET_DB_URL }}
      VALET_DB_PORT: ${{ secrets.VALET_DB_PORT }}
      VALET_REFRESHTOKENTIME: ${{ secrets.VALET_REFRESHTOKENTIME }}
      VALET_ACCESSTOKENTIME: ${{ secrets.VALET_ACCESSTOKENTIME }}
    steps:
     - name: enviro test
       run: echo $VALET_DB_URL
       
     - name: Checkout
       uses: actions/checkout@v3

     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
          java-version: '11'
          distribution: 'temurin'
 
     - name: Set Gradle
       run: chmod +x gradlew

     - name: Build with Gradle
       run: ./gradlew build
       shell: bash    
       
     - name: location for Delivery
       uses: appleboy/scp-action@master
       with:
         host: ${{ secrets.HOST_IP }}
         username: ${{ secrets.HOST_ID }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.HOST_PORT }}
         source: "build/libs/*.jar"
         target: "source"
         rm: true


     - name: executing app stop
       uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
       with:
         host: ${{ secrets.HOST_IP }}
         username: ${{ secrets.HOST_ID }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.HOST_PORT }}
         script_stop: true
         script: |
                ./app_stop.sh      
                sleep 3
     - name: executing app start
       uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
       env:
          VALET_SECRET_KEY: ${{ secrets.VALET_SECRET_KEY }}
          VALET_DB_USERNAME: ${{ secrets.VALET_DB_USERNAME }}
          VALET_DB_PASSWORD: ${{ secrets.VALET_DB_PASSWORD }}
          VALET_DB_URL: ${{ secrets.VALET_DB_URL }}
          VALET_DB_PORT: ${{ secrets.VALET_DB_PORT }}
          VALET_REFRESHTOKENTIME: ${{ secrets.VALET_REFRESHTOKENTIME }}
          VALET_ACCESSTOKENTIME: ${{ secrets.VALET_ACCESSTOKENTIME }}
       with:
         envs: VALET_SECRET_KEY,VALET_DB_USERNAME,VALET_DB_PASSWORD,VALET_DB_URL,VALET_DB_PORT,VALET_REFRESHTOKENTIME,VALET_ACCESSTOKENTIME
         host: ${{ secrets.HOST_IP }}
         username: ${{ secrets.HOST_ID }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.HOST_PORT }}
         script: |
               export VALET_SECRET_KEY=$VALET_SECRET_KEY
               export VALET_DB_USERNAME=$VALET_DB_USERNAME
               export VALET_DB_PASSWORD=$VALET_DB_PASSWORD
               export VALET_DB_URL=$VALET_DB_URL
               export VALET_DB_PORT=$VALET_DB_PORT
               export VALET_REFRESHTOKENTIME=$VALET_REFRESHTOKENTIME
               export VALET_ACCESSTOKENTIME=$VALET_ACCESSTOKENTIME
               
               nohup java -jar /root/source/build/libs/*.jar > nohup.out 2> nohup.err < /dev/null &
